CompanyInvoicesWeb/Controllers/InvoiceController.cs
using CompanyInvoicesWeb.App_Start;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL = CompanyInovicesEF.DAL;
using VM = CompanyInvoicesWeb.Models;
using DB = CompanyInovicesEF.Tables;

namespace CompanyInvoicesWeb.Controllers
{
    public class InvoiceController : Controller
    {
        DAL.Company companyDAL = new DAL.Company();
        DAL.Invoice invoiceDAL = new DAL.Invoice();
        // GET: Invoice
        public ActionResult Index()
        {
            List<CompanyInvoicesWeb.Models.Inovice> invoiceVM = new List<CompanyInvoicesWeb.Models.Inovice>();
            var dbCompanies = invoiceDAL.GetAllInvoices();

            dbCompanies.ForEach(item =>
            {
                invoiceVM.Add(MapperConfig.Mapper.Map<VM.Inovice>(item));
            });
            return View(invoiceVM);
        }

        public ActionResult AddNewInvoice()
        {
            var charges =  invoiceDAL.GetAllCharges();
            var companies = companyDAL.GetAllCompanies();
            var vmChargesList = new List<VM.Charge>();
            var vmCompanyList = new List<VM.Company>();
            var invoice = new VM.Inovice();

            charges.ForEach(a => vmChargesList.Add(MapperConfig.Mapper.Map<VM.Charge>(a)));
            companies.ForEach(a => vmCompanyList.Add(MapperConfig.Mapper.Map<VM.Company>(a)));

            invoice.Charges = vmChargesList;
            invoice.Companies = vmCompanyList;
            return View(invoice);
        }
        [HttpPost]
        public ActionResult AddNewInvoice(VM.Inovice invoice)
        {
            var vmChargesList = new List<VM.Charge>();
            var vmCompaniesList = new List<VM.Company>();

            var charges = invoiceDAL.GetAllCharges();
            var companies = companyDAL.GetAllCompanies();

            charges.ForEach(a => vmChargesList.Add(MapperConfig.Mapper.Map<VM.Charge>(a)));
            companies.ForEach(a => vmCompaniesList.Add(MapperConfig.Mapper.Map<VM.Company>(a)));

            invoiceDAL.AddNewInvoice(MapperConfig.Mapper.Map<DB.CompanyInvoice>(invoice));
            return View(new VM.Inovice { Charges = vmChargesList, Companies = vmCompaniesList });
        }
        public ActionResult InvoiceDetails(int ID, string companyName)
        {
            var invoice = invoiceDAL.GetInvoiceById(ID, companyName);

            return View(MapperConfig.Mapper.Map<VM.Inovice>(invoice));
        }

        [HttpPost]
        public ActionResult DeleteInvoice(int ID, string companyName)
        {
            invoiceDAL.DeleteInvoice(ID, companyName);

            return RedirectToAction("Index");
        }
        public ActionResult EditInvoice(int id, string companyName)
        {
            var invoice = invoiceDAL.GetInvoiceById(id, companyName);

            return View(MapperConfig.Mapper.Map<VM.Inovice>(invoice));
        }

        [HttpPost]
        public ActionResult EditInvoice(VM.Inovice invoice)
        {

            invoiceDAL.EditInvoice(MapperConfig.Mapper.Map<DB.CompanyInvoice>(invoice));
            return RedirectToAction("Index");
        }
    }
}

CompanyInvoicesWeb/Views/Invoice/AddNewInvoice.cshtml
@model CompanyInvoicesWeb.Models.Inovice

@{
    ViewBag.Title = "AddNewInvoice";
}

<h2>AddNewInovoice</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Inovice</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ChargeID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ChargeID, new SelectList(Model.Charges, "ID", "Name"), htmlAttributes: new { @class = "form-control col-md-2" })
                @Html.ValidationMessageFor(model => model.ChargeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CompanyName, new SelectList(Model.Companies, "CompanyName", "CompanyName"), htmlAttributes: new { @class = "form-control col-md-2" })
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InvoiceDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InvoiceDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InvoiceDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CompanyInvoicesWeb/Views/Invoice/DeleteInvoice.cshtml
@model CompanyInvoicesWeb.Models.Inovice

@{
    ViewBag.Title = "DeleteInvoice";
}

<h2>DeleteInvoice</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Inovice</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ChargeID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChargeID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InvoiceDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InvoiceDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CompanyInvoicesWeb/Views/Invoice/EditInvoice.cshtml
@model CompanyInvoicesWeb.Models.Inovice

@{
    ViewBag.Title = "EditInvoice";
}

<h2>EditInvoice</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Inovice</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CompanyInvoiceId)

        <div class="form-group">
            @Html.LabelFor(model => model.ChargeID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ChargeID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ChargeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InvoiceDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InvoiceDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InvoiceDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CompanyInvoicesWeb/Views/Invoice/Index.cshtml
@{
    ViewBag.Title = "Invoices";
}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<h2>Index</h2>
@using (Html.BeginForm("AddNewInvoice", "Invoice", FormMethod.Get))
{

    <button class="btn btn-primary">Add Invoice</button>
}

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Company Name</th>
            <th scope="col">Invoice Date</th>
            <th scope="col">Start Date</th>
            <th scope="col">End Date</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var item in Model)
            {
                <tr>
                    <td> @item.CompanyName</td>
                    <td>@item.InvoiceDate</td>
                    <td>@item.StartDate</td>
                    <td>@item.EndDate</td>
                    <td>
                        <a href="EditInvoice/@item.CompanyInvoiceId/@item.CompanyName"><i class="fa fa-pencil-square-o fa-lg" aria-hidden="true"></i></a>
                    </td>
                    <td><a href="InvoiceDetails/@item.CompanyInvoiceId/@item.CompanyName"><i class="fa fa-info-circle fa-lg" aria-hidden="true"></i></a></td>
                    <td>
                        @using (Html.BeginForm("DeleteInvoice", "Invoice", new {id = item.CompanyInvoiceId, companyName = item.CompanyName }))
                        {
                            <input type="submit" />
                        }
                    </td>
                </tr>
            };

        }

    </tbody>
</table>

CompanyInvoicesWeb/Views/Invoice/InvoiceDetails.cshtml
@model CompanyInvoicesWeb.Models.Inovice

@{
    ViewBag.Title = "InvoiceDetails";
}

<h2>InvoiceDetails</h2>

<div>
    <h4>Inovice</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ChargeID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChargeID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InvoiceDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InvoiceDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { @*id = Model.ID*@ }) |
    @Html.ActionLink("Back to List", "Index")
</p>